version: 2

updates:
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "weekly"
      labels:
          - "dependencies"
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "weekly"
      labels:
          - "dependencies"
    - package-ecosystem: "pip"
      directory: "docs/"
      schedule:
          interval: "weekly"
      labels:
          - "dependencies"
