version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "Dobby233Liu"
    reviewers:
      - "Dobby233Liu"
    labels:
      - "dependencies"
