site_name: node-bullshit-generator
theme: readthedocs
nav:
    - Home: "README.md"
    - "Using the Library":
        - "lib.md"
        #- 'dict.md'
        #- 'libref.md'
    - "cli.md"
    #- "Other Stuff":
        #- 'packeddicts.md'
