on:
    push:
    pull_request:

jobs:
    bundle_plus_min:
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[nobundle]')"
        steps:
            - uses: actions/checkout@v2
            - uses: fregante/setup-git-token@v1
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                name: GitHub Actions
            - run: "npm install"
            # fix
            - run: "git pull --tags -f"
            - run: "npm run bundle+min"
            - run: "git add . && git commit -m \"[nobundle][newgrass] Automatical bundled the library\""
            - uses: ad-m/github-push-action@master
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}