on:
    push:
    pull_request:

jobs:
    bundle_plus_min:
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[nobundle]')"
        steps:
            - uses: actions/checkout@v2
            - uses: fregante/setup-git-token@v1
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                # use bot creds rather than org creds
                name: github-actions[bot]
                email: 41898282+github-actions[bot]@users.noreply.github.com
            - run: npm install
            - run: "git pull --tags -f" # checklater
            - run: npm run beautify
              #continue-on-error: true
            - run: npm run bundle+min
              #continue-on-error: true
            - run: git add . && git commit -m "[nobundle] Bundle library and beautify"
              id: commit-files
              continue-on-error: true
            - uses: ad-m/github-push-action@master
              continue-on-error: true
              if: "steps.commit-files.outcome != 'failure'"
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                branch: ${{ github.ref }}
