on: [push]
jobs:
    bundle_plus_min:
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[nobundle]')"
        steps:
            - run: "npm install"
            - run: "npm run bundle+min"
            - run: |
                git config --local user.email "action@github.com"
                git config --local user.name "GitHub Action"
                git commit -m "[nobundle][newgrass] bundle" -a
            - uses: ad-m/github-push-action@master
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}