on: [push]

permissions:
    # We beautify everything, including workflows
    workflows: write

jobs:
    beautify:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: fregante/setup-git-token@v1
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                name: github-actions[bot]
                email: 41898282+github-actions[bot]@users.noreply.github.com
            - run: npm install
            - run: npx prettier --check .
              id: check-beautify
              continue-on-error: true
            - run: npx prettier --write .
              if: "steps.check-beautify.outcome == 'failure' && !contains(github.event.head_commit.message, '[skip beautify]')"
            - run: git add . && git commit -m "Beautify source files"
              id: commit-files
              continue-on-error: true
            - uses: ad-m/github-push-action@master
              continue-on-error: true
              if: "steps.commit-files.outcome != 'failure'"
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                branch: ${{ github.ref }}
            - name: Error now if errored before
              run: exit 1
              if: "steps.check-beautify.outcome == 'failure'"
