on:
    push:
        paths:
          - 'src/**'
          - 'bin/**'
          - '**/*.json'

jobs:
    beautify:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: fregante/setup-git-token@v1
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                name: github-actions[bot]
                email: 41898282+github-actions[bot]@users.noreply.github.com
            - run: npm install
            - run: npm run beautify
            - run: git add . && git commit -m "Beautify source files"
              id: commit-files
              continue-on-error: true
            - uses: ad-m/github-push-action@master
              continue-on-error: true
              if: "steps.commit-files.outcome != 'failure'"
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                branch: ${{ github.ref }}
